---
services:
  frontend:
    container_name: "TYSONCLOUD-frontent"
    build: "./frontend"
    ports:
      - "3000:3000"

  backend:
    container_name: "TYSONCLOUD-backend"
    build: "./backend"
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
