name: API test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Pytest unit tests
        working-directory: ./backend
        run: "pytest test_app.py"
