name: Docker build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build frontend Docker image
        working-directory: ./frontend
        run: docker build -t timmijinks/tysoncloud-frontend .

      - name: Build backend Docker image
        working-directory: ./backend
        run: docker build -t timmijinks/tysoncloud-backend .
