name: Docker build

on: [push]

jobs: 
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - run: npm set registry https://registry.npmjs.org/
      - run: node install
      
      - name: Build frontend Docker image
        run: docker build -t timmijinks/tysoncloud-frontend ${{github.workspace}}/frontend
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Build backend Docker image
        run: docker build -t timmijinks/tysoncloud-backend .
    
     
