name: Docker build

on: [push]

jobs: 
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      
      - name: Build frontend Docker image
        run: docker build -t timmijinks/tysoncloud-frontend --debug --target builder .
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Build backend Docker image
        run: docker build -t timmijinks/tysoncloud-backend .
    
     
