name: Docker build

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      
      - run: bun install ${{github.workspace}}/frontend       
      - name: Build frontend Docker image
        run: docker build -t timmijinks/tysoncloud-frontend ${{github.workspace}}/frontend
      
      - name: Build backend Docker image
        run: docker build -t timmijinks/tysoncloud-backend ${{github.workspace}}/backend
    
     
